### ISSUE TITLE
Application not responding when adding first item to empty column.  

### ISSUE THREAD

**Issue by ganeshbahirat** [jakebonk/BoardView#2]
> 
> 
> E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                       Process: com.extentia.ecomapp, PID: 17217
>                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.widget.ScrollView.getChildAt(int)' on a null object reference
>                                                                           at com.allyants.boardview.BoardView.handleItemSwitchHorizontal(BoardView.java:377)
>                                                                           at com.allyants.boardview.BoardView.handleColumnDragEvent(BoardView.java:272)
>                                                                           at com.allyants.boardview.BoardView.onTouchEvent(BoardView.java:214)
>                                                                           at android.view.View.dispatchTouchEvent(View.java:9942)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
>                                                                           at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
>                                                                           at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
>                                                                           at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
>                                                                           at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
>                                                                           at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
>                                                                           at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
>                                                                           at android.view.View.dispatchPointerEvent(View.java:10162)
>                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4434)
>                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
>                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
>                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
>                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
>                                                                           at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3995)
>                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
>                                                                           at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4052)
>                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
>                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
>                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
>                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
>                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
>                                                                           at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6210)
>                                                                           at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6184)
>                                                                           at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6145)
>                                                                           at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6313)
>                                                                           at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
>                                                                           at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
>                                                                           at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
> 07-04 16:04:56.454 17217-17217/com.extentia.ecomapp E/AndroidRuntime:     at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6284)
>                                                                           at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6336)
>                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
>                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:683)
>                                                                           at android.view.Choreographer.doFrame(Choreographer.java:613)
>                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
>                                                                           at android.os.Handler.handleCallback(Handler.java:751)
>                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                           at android.os.Looper.loop(Looper.java:154)
>                                                                           at android.app.ActivityThread.main(ActivityThread.java:6077)
>                                                                           at java.lang.reflect.Method.invoke(Native Method)
>                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
>                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by jakebonk** [comment]
Which build version of the app were you using?

**Comment by jakebonk** [comment]
I just updated the code, please let me know if it continues to crash!

**Comment by ganeshbahirat** [comment]
I am using version **1.1.7**

**Comment by jakebonk** [comment]
I believe I fixed both this and your other issue in build 1.1.9. On a seperate not it seemed like android studio wasn't pushing the correct gradle to the app I'm using this library on but worked after uninstalling and reinstalling my app.
