### ISSUE TITLE
Sometime giving IndexOutOfBound exception while moving items to other columns.

### ISSUE THREAD

**Issue by ganeshbahirat** [jakebonk/BoardView#3]
> Index: 4, Size: 0
>                                                                           at java.util.ArrayList.get(ArrayList.java:411)
>                                                                           at com.allyants.boardview.BoardView.touchEventsCancelled(BoardView.java:508)
>                                                                           at com.allyants.boardview.BoardView.handleColumnDragEvent(BoardView.java:316)
>                                                                           at com.allyants.boardview.BoardView.onTouchEvent(BoardView.java:235)
>                                                                           at android.view.View.dispatchTouchEvent(View.java:9942)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
>                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
>                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
>                                                                           at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:411)
>                                                                           at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1810)
>                                                                           at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
>                                                                           at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
>                                                                           at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
>                                                                           at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
>                                                                           at android.view.View.dispatchPointerEvent(View.java:10162)
>                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4434)
>                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
>                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
>                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
>                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
>                                                                           at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3995)
>                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
>                                                                           at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4052)
>                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
>                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3902)
>                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3868)
>                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3876)
>                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3849)
>                                                                           at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6210)
>                                                                           at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6184)
>                                                                           at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6145)
>                                                                           at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6313)
>                                                                           at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
>                                                                           at android.os.MessageQueue.nativePollOnce(Native Method)
>                                                                           at android.os.MessageQueue.next(MessageQueue.java:323)
>                                                                           at android.os.Looper.loop(Looper.java:136)
>                                                                           at android.app.ActivityThread.main(ActivityThread.java:6077)
>                                                                           at java.lang.reflect.Method.invoke(Native Method)
> 07-04 16:20:30.160 24379-24379/com.extentia.ecomapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
>                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by jakebonk** [comment]
This should have been fixed in the last update, so please let me know if you continue having any problems!
