### ISSUE TITLE
Android Kanban Board Collaboration

### ISSUE THREAD

**Issue by tbastoss** [jakebonk/BoardView#4]
Hi, 

I am working on a project at Universideda Federal Rural de Pernambuco (UFRPE) in Brazil. My team needs a kanban board for an android app and yours seems to be the best choice. Although, while studying your API, I realised that it'll be necessery to make some programming changes to work the way our project needs it to be.
Is your API open source ? Moreover, can I have access to your code?

Our idea is to improve the layout of the board and its cards and if we manage to do it we can send it to you to collaborate with your work.

Thanks for your time,
Best Regards.

**Comment by jakebonk** [comment]
Sure! The code is all open-source so feel free to edit it and use it however you like! If you do make changes that make the code better just make a pull request when it's done and I'll check it out and merge it.

**Comment by rizwanjillani** [comment]
Hi,
@jakebonk 
I am working on a project and needs to add drag n drop in this project but while dragging an item on another with more height starts flickering, Please help regarding this issue.
Thanks for your time,
Best Regards.
