### ISSUE TITLE
Snapshot location is outside the visible view 

### ISSUE THREAD

**Issue by dhruvappstack** [jakebonk/BoardView#5]
I am using boardview to implement Kanban board . Everything is working fine .There is one issue .
Follow these steps to reproduce that bug:
- Add lot of data more than 50 cards in each Vertical List of Boardview 
- Scroll the list so that pick some card in middle or nearest to those 50 cards . 
- When you pick the card than it will not show (hidden or location is somewhere else)while the functionality working fine after dropping the card 
Can you help me to fix this issue ?

**Comment by dhruvappstack** [comment]
Fixed the issue 👍 
 mHoverCellCurrentBounds.offsetTo(offsetX,
                            mLastEventY - mobileView.getHeight()-60);
Line number : 352

**Comment by rizwanjillani** [comment]
Hi,
@EonKid 
I am working on a project and needs to add drag n drop in this project but while dragging an item on another with more height starts flickering, Please help regarding this issue.
Thanks for your time,
Best Regards.
