### ISSUE TITLE
Restrict the max number of item in list after drag and drop

### ISSUE THREAD

**Issue by raghunandankavi2010** [jakebonk/BoardView#8]
Is there a way to restrict the number of items in a Column after drag and drop. Like if i want only 5 items in a column and if i drag a 6th item column should lock

**Comment by jakebonk** [comment]
I added this in build 1.3.3 just set maxItemCount in your BoardAdapter class to return 5 and it should work!

**Comment by EdgardoLopezC** [comment]
Hi, how i can change limit maxItemCount?
