### ISSUE TITLE
DragItemStartCallback parameters

### ISSUE THREAD

**Issue by AlexSicoe** [jakebonk/BoardView#9]
Hi. I've noticed when logging endDrag that startItemPos shows the column position, and startColumnPos shows the Item position. So in that sense, they're twisted.  My temporary workaround was to switch the order like this : 
```
@Override
            public void endDrag(View view, int startColumnPos, int startItemPos, int endItemPos, int endColumnPos) {...}
```
Both startDrag and endDrag are affected. changedPosition seems ok
Also endItemPos and endColumnPos are ok. Only start positions are affected

**Comment by jakebonk** [comment]
Sorry it took so long to fix this little issue. This is fixed as of the latest commit! 
Thanks!
